DROP TABLE PROJECT;;/*SkipError*/
CREATE TABLE PROJECT(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT 'id' ,
    DOCK_CODE VARCHAR(32)    COMMENT '对接码' ,
    NAME VARCHAR(32)    COMMENT '项目名称' ,
    SHARE_FEE DECIMAL(32,8)   DEFAULT 0 COMMENT '共享价格' ,
    DOCK_FEE DECIMAL(32,8)   DEFAULT 0 COMMENT '对接价格' ,
    TYPE_ID INT    COMMENT '类型' ,
    TYPE_NAME VARCHAR(32)    COMMENT '类型名称' ,
    NUMBER INT   DEFAULT 0 COMMENT '可做个数' ,
    ONLINE_NUMBER INT   DEFAULT 0 COMMENT '在线数量' ,
    USE_NUMBER INT   DEFAULT 0 COMMENT '可用数量' ,
    KEYWORD VARCHAR(32)    COMMENT '关键字' ,
    DOCK_PERSON_NUMBER INT    COMMENT '对接人数' ,
    STATUS INT   DEFAULT 0 COMMENT '状态(0 待审核 1 启用 2 禁用 默认0)' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '项目 ';;

ALTER TABLE PROJECT COMMENT '项目';;
DROP TABLE PROJECT_TYPE;;/*SkipError*/
CREATE TABLE PROJECT_TYPE(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT 'id' ,
    NAME VARCHAR(32)    COMMENT '类型名称' ,
    CREATED_TIME DATETIME   DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
    UPDATED_TIME DATETIME   DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '项目类型 ';;

ALTER TABLE PROJECT_TYPE COMMENT '项目类型';;
DROP TABLE MERCHANT;;/*SkipError*/
CREATE TABLE MERCHANT(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT 'id' ,
    USERNAME VARCHAR(32)    COMMENT '用户名' ,
    PASSWORD VARCHAR(32)    COMMENT '密码' ,
    REAL_NAME VARCHAR(32)    COMMENT '真实姓名' ,
    BALANCE DECIMAL(32,8)   DEFAULT 0 COMMENT '余额（元）' ,
    PHONE VARCHAR(32)    COMMENT '电话' ,
    TYPE_ID INT    COMMENT '卡商类型' ,
    STATUS INT   DEFAULT 0 COMMENT '账户状态(0 启用 1 禁用 默认0)' ,
    CARD_NUMBER INT   DEFAULT 0 COMMENT '号码数量' ,
    CREATED_TIME DATETIME   DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
    UPDATED_TIME DATETIME   DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '卡商 ';;

ALTER TABLE MERCHANT COMMENT '卡商';;
DROP TABLE USER;;/*SkipError*/
CREATE TABLE USER(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT 'id' ,
    USERNAME VARCHAR(32)    COMMENT '用户名' ,
    REAL_NAME VARCHAR(32)    COMMENT '真实姓名' ,
    LEVEL INT   DEFAULT 1 COMMENT '等级' ,
    BALANCE DECIMAL(32,8)   DEFAULT 0 COMMENT '余额（元）' ,
    QQ VARCHAR(32)    COMMENT 'QQ' ,
    PHONE VARCHAR(32)    COMMENT '电话' ,
    STATUS INT   DEFAULT 0 COMMENT '账户状态(0 启用 1 禁用 默认0)' ,
    INVITOR_ID INT    COMMENT '邀请人id' ,
    INVITOR_USERNAME VARCHAR(32)    COMMENT '邀请人' ,
    CREATED_TIME DATETIME   DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
    UPDATED_TIME DATETIME   DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '用户 ';;

ALTER TABLE USER COMMENT '用户';;
DROP TABLE USER_LEVEL;;/*SkipError*/
CREATE TABLE USER_LEVEL(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT 'id' ,
    NAME VARCHAR(32)    COMMENT '用户等级' ,
    NUMBER INT   DEFAULT 0 COMMENT '获取数量' ,
    DISCOUNT INT   DEFAULT 100 COMMENT '折扣%' ,
    POINT INT   DEFAULT 0 COMMENT '积分' ,
    CREATED_TIME DATETIME   DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
    UPDATED_TIME DATETIME   DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '用户等级 ';;

ALTER TABLE USER_LEVEL COMMENT '用户等级';;
DROP TABLE USER_PROJECT;;/*SkipError*/
CREATE TABLE USER_PROJECT(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT 'id' ,
    USER_ID INT    COMMENT '用户id' ,
    PROJECT_ID INT    COMMENT '项目id' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '用户专属项目 ';;

ALTER TABLE USER_PROJECT COMMENT '用户专属项目';;
